# -*- coding: utf-8 -*-
"""Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O3tp2kULx5dByCBpVhdhVabYCD2VkIQ1
"""

a=int(input("Enter the Value of a :"))
b=int(input("Enter the Value of b :"))
c=a+b
print("The Addition of a and b :",c)

name=input("Enter your Name :")
age=input("Enter your Age :")
degree=input("Enter your Qualification :")
job=input("Enter your Job :")
print("\n\tYour Info")
print("Name          :",name)
print("Age           :",age)
print("Qualification :",degree)
print("Job           :",job)

name=input("Enter Your Name :")
Reg_no=input("Enter Your Register Number :")
Mark1=int(input("Enter Your Mark 1 :"))
Mark2=int(input("Enter Your Mark 2 :"))
Mark3=int(input("Enter Your Mark 3 :"))
Mark4=int(input("Enter Your Mark 4 :"))
Tot=Mark1+Mark2+Mark3+Mark4
Avg=Tot/4
print("\n\tMark List")
print("Name    :",name)
print("Reg.No. :",Reg_no)
print("Total   :",Tot)
print("Average :",Avg)